/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // mySidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mySidebar: {
    'Course Info': [
      'attribution',
      'policies',
      '236topics',
      'algoverview',
    ],
    Logic: [
      'logic/intro',
      'logic/props',
      'logic/boolean',
      'logic/circuits',
      'logic/simplify',
      'logic/components',
      'logic/preds',
      'logic/deduction',
      'logic/pred-deduction',
      'logic/induction',
      'logic/recursion',
      'logic/sequential',
      'logic/state',
    ],
    Sets: [
      'sets/concepts',
      'sets/algebra',
      'sets/programming',
      'sets/functions',
      'sets/relations',
      'sets/database',
    ],
    'Functional Programming': [
      'fp/intro',
      'fp/types',
      'fp/map-reduce',
      'fp/doodle',
      'fp/state',
      'fp/parser-comb',
      'fp/lambda',
    ],
    'Lists, Trees, and Graphs': [
      'ds/lists',
      'ds/recurrence',
      'ds/verification',
      'ds/trees',
      'ds/bst',
      'ds/graphs',
    ],
    'Formal Languages': [
      'lang/languages',
      'lang/regexp',
      'lang/regexpapp',
      'lang/fsa',
      'lang/nfa',
      'lang/fsareg',
      'lang/cfg',
      'lang/bnf',
      'lang/parsing',
      'lang/pda',
      'lang/tm',
      'lang/computability',
      'lang/halting',
    ],
    Features: [
      'scala',
      'styleGuide',
    ],
    'Supplementary Topics': [
        'reason',
        'ocaml',
        '233topics',
        'overview',
        'fp/overview',
        'methods',
        'fp/curry',
        'fp/natded',
    ],
  },
};

export default sidebars;
